v4l2-ctl -d /dev/video0 --set-ctrl=brightness=0
v4l2-ctl -d /dev/video0 --set-ctrl=contrast=50
v4l2-ctl -d /dev/video0 --set-ctrl=saturation=64
v4l2-ctl -d /dev/video0 --set-ctrl=hue=0
v4l2-ctl -d /dev/video0 --set-ctrl=white_balance_temperature_auto=1
v4l2-ctl -d /dev/video0 --set-ctrl=white_balance_temperature=6500
v4l2-ctl -d /dev/video0 --set-ctrl=gamma=100
v4l2-ctl -d /dev/video0 --set-ctrl=gain=0
v4l2-ctl -d /dev/video0 --set-ctrl=sharpness=3
v4l2-ctl -d /dev/video0 --set-ctrl=backlight_compensation=0
v4l2-ctl -d /dev/video0 --set-ctrl=exposure_absolute=157
v4l2-ctl -d /dev/video0 --set-ctrl=exposure_auto=3
v4l2-ctl -d /dev/video0 --set-ctrl=exposure_auto_priority=0

v4l2-ctl -d /dev/video2 --set-ctrl=brightness=0
v4l2-ctl -d /dev/video2 --set-ctrl=contrast=50
v4l2-ctl -d /dev/video2 --set-ctrl=saturation=64
v4l2-ctl -d /dev/video2 --set-ctrl=hue=0
v4l2-ctl -d /dev/video2 --set-ctrl=white_balance_temperature_auto=1
v4l2-ctl -d /dev/video2 --set-ctrl=white_balance_temperature=6500
v4l2-ctl -d /dev/video2 --set-ctrl=gamma=100
v4l2-ctl -d /dev/video2 --set-ctrl=gain=0
v4l2-ctl -d /dev/video2 --set-ctrl=sharpness=3
v4l2-ctl -d /dev/video2 --set-ctrl=backlight_compensation=0
v4l2-ctl -d /dev/video2 --set-ctrl=exposure_absolute=157
v4l2-ctl -d /dev/video2 --set-ctrl=exposure_auto=3
v4l2-ctl -d /dev/video2 --set-ctrl=exposure_auto_priority=0


v4l2-ctl -d /dev/video4 --set-ctrl=brightness=0
v4l2-ctl -d /dev/video4 --set-ctrl=contrast=50
v4l2-ctl -d /dev/video4 --set-ctrl=saturation=90
v4l2-ctl -d /dev/video4 --set-ctrl=hue=0
v4l2-ctl -d /dev/video4 --set-ctrl=white_balance_temperature_auto=1
v4l2-ctl -d /dev/video4 --set-ctrl=white_balance_temperature=6500
v4l2-ctl -d /dev/video4 --set-ctrl=gamma=100
v4l2-ctl -d /dev/video4 --set-ctrl=gain=0
v4l2-ctl -d /dev/video4 --set-ctrl=sharpness=3
v4l2-ctl -d /dev/video4 --set-ctrl=backlight_compensation=0
v4l2-ctl -d /dev/video4 --set-ctrl=exposure_absolute=157
v4l2-ctl -d /dev/video4 --set-ctrl=exposure_auto=3
v4l2-ctl -d /dev/video4 --set-ctrl=exposure_auto_priority=0

v4l2-ctl -d /dev/video6 --set-ctrl=brightness=10
v4l2-ctl -d /dev/video6 --set-ctrl=contrast=50
v4l2-ctl -d /dev/video6 --set-ctrl=saturation=64
v4l2-ctl -d /dev/video6 --set-ctrl=hue=0
v4l2-ctl -d /dev/video6 --set-ctrl=white_balance_temperature_auto=1
v4l2-ctl -d /dev/video6 --set-ctrl=white_balance_temperature=6500
v4l2-ctl -d /dev/video6 --set-ctrl=gamma=100
v4l2-ctl -d /dev/video6 --set-ctrl=gain=0
v4l2-ctl -d /dev/video6 --set-ctrl=sharpness=3
v4l2-ctl -d /dev/video6 --set-ctrl=backlight_compensation=0
v4l2-ctl -d /dev/video6 --set-ctrl=exposure_absolute=157
v4l2-ctl -d /dev/video6 --set-ctrl=exposure_auto=3
v4l2-ctl -d /dev/video6 --set-ctrl=exposure_auto_priority=0
